name: release
run-name: Create GitHub release

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    needs:
      project_version
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: Create a GitHub release
        uses: ncipollo/release-action@v1
        with:
          tag: ${{ format('v{0}', ${{needs.project_version.outputs.project_version}} ) }}
          name: Release ${{needs.project_version.outputs.project_version}}
