name: tag
run-name: Add git tag

on:
  workflow_call

jobs:
  tag:
    needs:
      project_version
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: Create and push version tag
        uses: mathieudutour/github-tag-action@v6.2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          custom_tag: ${{ needs.project_version.outputs.project_version }}
