name: Add version tag

on:
  - workflow_call

jobs:
  tag:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get -y install coinor-libipopt-dev
      - name: Set up Python
        uses: actions/setup-python@v5
      - name: Install poetry
        uses: abatilo/actions-poetry@v2
      - name: Get version from poetry
        id: version
        run: |
          echo "project_version=$(poetry version --short)" >> "$GITHUB_ENV"
      - name: Create and push version tag
        uses: mathieudutour/github-tag-action@v6.2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          custom_tag: ${{ env.project_version }}
      - name: Create GitHub release
        uses: ncipollo/release-action@v1
        with:
          tag: ${{ format('v{0}', env.project_version) }}
          name: Release ${{ env.project_version }}
